/** Caminhos em /public — bandeiras .webp (funcionam em Windows, Mac, etc.). */
export const countryFlagImages: Record<string, string> = {
  Argentina: "/argentina.webp",
  Brasil: "/brasil.webp",
  Uruguai: "/uruguai.webp",
  Paraguai: "/paraguai.webp",
  Colômbia: "/colombia.webp",
  Colombia: "/colombia.webp",
  Equador: "/equador.webp",
  México: "/mexico.webp",
  Mexico: "/mexico.webp",
  "Estados Unidos da América": "/estadosunidos.webp",
  EUA: "/estadosunidos.webp",
  Canadá: "/canada.webp",
  Canada: "/canada.webp",
  Panamá: "/panama.webp",
  Panama: "/panama.webp",
  Haiti: "/haiti.webp",
  Haíti: "/haiti.webp",
  Curaçao: "/curacao.webp",
  Curacao: "/curacao.webp",
  Alemanha: "/alemanha.webp",
  Espanha: "/espanha.webp",
  França: "/franca.webp",
  Franca: "/franca.webp",
  Inglaterra: "/inglaterra.webp",
  Portugal: "/portugal.webp",
  Holanda: "/holanda.webp",
  "Países Baixos": "/holanda.webp",
  Bélgica: "/belgica.webp",
  Belgica: "/belgica.webp",
  Croácia: "/croacia.webp",
  Croacia: "/croacia.webp",
  "Bósnia e Herzegovina": "/bosnia.webp",
  "Bosnia e Herzegovina": "/bosnia.webp",
  Suíça: "/suica.webp",
  Suica: "/suica.webp",
  Áustria: "/austria.webp",
  Austria: "/austria.webp",
  Suécia: "/suecia.webp",
  Suecia: "/suecia.webp",
  Escócia: "/escocia.webp",
  Escocia: "/escocia.webp",
  Noruega: "/noruega.webp",
  Turquia: "/turquia.webp",
  "República Tcheca": "/republicatcheca.webp",
  "Republica Tcheca": "/republicatcheca.webp",
  Tchequia: "/republicatcheca.webp",
  Marrocos: "/marrocos.webp",
  Senegal: "/senegal.webp",
  Tunísia: "/tunisia.webp",
  Tunisia: "/tunisia.webp",
  Argélia: "/argelia.webp",
  Argelia: "/argelia.webp",
  Congo: "/congo.webp",
  "República do Congo": "/congo.webp",
  Gana: "/gana.webp",
  "Costa do Marfim": "/costadomarfim.webp",
  "África do Sul": "/africadosul.webp",
  "Africa do Sul": "/africadosul.webp",
  Egito: "/egito.webp",
  "Cabo Verde": "/caboverde.webp",
  Japão: "/japao.webp",
  Japao: "/japao.webp",
  "Coreia do Sul": "/coreiadosul.webp",
  Irã: "/ira.webp",
  Ira: "/ira.webp",
  "Arábia Saudita": "/arabaisaudita.webp",
  "Arabia Saudita": "/arabaisaudita.webp",
  Austrália: "/australia.webp",
  Australia: "/australia.webp",
  Catar: "/catar.webp",
  Iraque: "/iraque.webp",
  Jordânia: "/jordania.webp",
  Jordania: "/jordania.webp",
  Uzbequistão: "/uzbequistao.webp",
  Uzbequistao: "/uzbequistao.webp",
  "Nova Zelândia": "/novazelandia.webp",
  "Nova Zelandia": "/novazelandia.webp",
}

/** Fallback emoji quando não há imagem em /public. */
const countryFlagEmojis: Record<string, string> = {
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  Venezuela: "🇻🇪",
  Bolívia: "🇧🇴",
  "Costa Rica": "🇨🇷",
  Jamaica: "🇯🇲",
  Honduras: "🇭🇳",
  "El Salvador": "🇸🇻",
  Guatemala: "🇬🇹",
  "Trinidad e Tobago": "🇹🇹",
  Itália: "🇮🇹",
  Dinamarca: "🇩🇰",
  Polônia: "🇵🇱",
  Ucrânia: "🇺🇦",
  Sérvia: "🇷🇸",
  "País de Gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Grécia: "🇬🇷",
  Rússia: "🇷🇺",
  Nigéria: "🇳🇬",
  Camarões: "🇨🇲",
  "RD Congo": "🇨🇩",
  "República Democrática do Congo": "🇨🇩",
  Mali: "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "Emirados Árabes": "🇦🇪",
  China: "🇨🇳",
  Tailândia: "🇹🇭",
  Vietnã: "🇻🇳",
}

export function getCountryFlagSrc(countryName: string): string | null {
  return countryFlagImages[countryName] ?? null
}

export function getCountryFlagEmoji(countryName: string): string {
  return countryFlagEmojis[countryName] ?? "🏳️"
}

/** @deprecated Preferir `<CountryFlag />` — mantido para compatibilidade. */
export function getCountryFlag(countryName: string): string {
  if (getCountryFlagSrc(countryName)) return ""
  return countryFlagEmojis[countryName] ?? "🏳️"
}
