/** Nomes da odds-api.io → nomes usados na tabela teams. */
export const ODDS_API_TO_APP_TEAM_NAME: Record<string, string> = {
  Mexico: "México",
  "South Africa": "África do Sul",
  "Korea Republic": "Coreia do Sul",
  Czechia: "Republica Tcheca",
  Canada: "Canadá",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  USA: "Estados Unidos da América",
  "United States": "Estados Unidos da América",
  Paraguay: "Paraguai",
  Qatar: "Catar",
  Switzerland: "Suíça",
  Brazil: "Brasil",
  Morocco: "Marrocos",
  Haiti: "Haiti",
  Scotland: "Escócia",
  Australia: "Austrália",
  Turkiye: "Turquia",
  Turkey: "Turquia",
  Germany: "Alemanha",
  Curacao: "Curaçao",
  Curaçao: "Curaçao",
  Netherlands: "Holanda",
  Japan: "Japão",
  "Ivory Coast": "Costa do Marfim",
  "Côte d'Ivoire": "Costa do Marfim",
  Ecuador: "Equador",
  Belgium: "Bélgica",
  Egypt: "Egito",
  "IR Iran": "Irã",
  Iran: "Irã",
  "New Zealand": "Nova Zelândia",
  Spain: "Espanha",
  "Cape Verde": "Cabo Verde",
  "Saudi Arabia": "Arábia Saudita",
  Uruguay: "Uruguai",
  France: "França",
  Senegal: "Senegal",
  Iraq: "Iraque",
  Norway: "Noruega",
  Argentina: "Argentina",
  Algeria: "Argélia",
  Austria: "Áustria",
  Jordan: "Jordânia",
  Portugal: "Portugal",
  "DR Congo": "Congo",
  "Congo DR": "Congo",
  Colombia: "Colômbia",
  Uzbekistan: "Uzbequistão",
  England: "Inglaterra",
  Croatia: "Croácia",
  Ghana: "Gana",
  Panama: "Panamá",
  Sweden: "Suécia",
  Tunisia: "Tunísia",
}

export function oddsApiTeamToAppName(apiName: string): string {
  return ODDS_API_TO_APP_TEAM_NAME[apiName] ?? apiName
}
